### ISSUE TITLE
Missing semicolon on throw stmt

### ISSUE THREAD

**Issue by eridal** [ricardofbarros/semistandard-format#5]
input:

``` js
thisWorks()
this.works()
throw new Wont('-->')
```

output:

``` js
thisWorks();
this.works();
throw new Wont('-->')
```

**Comment by eridal** [comment]
is the project still maintained?

**Comment by Flet** [comment]
Looks like its falling behind a bit :(

I'll find some time to get things in sync with `standard-format`

Contributions are always welcome!

**Comment by fabiosantoscode** [comment]
Cannot reproduce this, do you still have this issue? Might have been fixed in the meantime.

**Comment by eridal** [comment]
Yes, I will go ahead and close this issue.
